site_name: My Docs  # Nom du site

# Métadonnées de description <300 caractères, et d'auteur pour toutes les pages du site
site_description: 
site_author: "Alexandre"

theme:
  #logo: "IMAGES/logo-kesia.jpeg" Permet de changer le logo
  name: material  # Nom du thème utilisé
  font: false  # RGPD ! pas de police Google donc de requêtes vers Google
  language: fr  # Langue du site (français)
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.select  # Permet de sélectionner du code
    - content.code.copy  # Ajoute un bouton pour copier le code
    - navigation.top  # Ajoute un bouton pour revenir en haut de la page

markdown_extensions:
  - abbr  # Abréviations
  - attr_list  # Listes d'attributs
  - meta  # Métadonnées
  - def_list  # Listes de définitions
  - pymdownx.emoji:  # Emojis
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:  # Coloration syntaxique
      anchor_linenums: true  # Ajoute des ancres pour les numéros de ligne
      line_spans: __span  # Utilise des spans pour les lignes
      pygments_lang_class: true  # Ajoute des classes de langage pour la coloration syntaxique
  - pymdownx.inlinehilite  # Coloration syntaxique en ligne
  - pymdownx.snippets  # Extraits de code
  - pymdownx.superfences  # Super clôtures pour le code
  - admonition  # Boîtes d'infos colorés (syntaxe Markdown : !!! info "Titre de l'info")
  - pymdownx.details  # Dérouler les admonitions

nav: #Création de la navigation à gauche
  - Accueil: index.md # 1 Niveau
  - MARKDOWN: # Nom de la bibliothèque
    - Installation: 2-MARKDOWN/1-Installation markdown.md #Chemin ou se trouve le fichié .md 2 Niveaux
    - Configuration: 2-MARKDOWN/2-Configuration markdown.md
    - Commandes Markdown: 2-MARKDOWN/3-Commandes.md
  - DATTO: 
    - Commandes: 3-DATTO/Commandes datto.md
  - BITDEFENDER:
    - Installation: 4-BITDEFENDER/1-Installation bitdefender.md
  - VEILLE TECHNO: 5-VEILLE TECHNO/Veille techno.md
  - Commandes pour les nuls: 6-COMMANDES POUR LES NULS/commandes pour les nuls.md









